config/routes.rb
Rails.application.routes.draw do

  resources :specializations

  resources :medical_consultations

  resources :doctors

  root 'welcome#index'

  resources :users

  get  "users/index"
  get  "/login"           => "users#login"
  post "/signin"          => "users#authenticate"
  get  "/signup"          => "users#new"
  get  "/logout"          => "users#logout"
  get  "/password"        => "users#password"
  post "/password_update" => "users#password_update"
end

app/models/user.rb
class User < ActiveRecord::Base
  before_create :encrypt_password

  validates :email,    :presence =>true, :uniqueness=>true
  validates :email,     format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :name,     :presence =>true, :uniqueness=>true
  validates :password, :presence =>true, :length => { :minimum => 5, :maximum => 40 }, :confirmation => true

  def self.md5(text)
    Digest::MD5.hexdigest(text)
  end

  def encrypt_password
    if password.present?
      self.password = Digest::MD5.hexdigest(self.password)
    end
  end

  def self.authenticate(email, password)
    user = find_by_email(email)
    user if user && user.password == md5(password)
  end

  def admin?
    self.role == 'admin'
  end

  private

  def generate_digest_token
    Digest::SHA1.hexdigest(SecureRandom.base64)
  end
end

app/controllers/users_controller.rb
# encoding : utf-8
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  before_filter :ensure_authentication, :only => [:edit, :update, :destroy, :index, :show]

  def login
  end

  def index
    @users = User.order(:name, :role)
    @new_user = User.new
    respond_to do |format|
      format.html
    end
  end

  def new
    @user = User.new
  end

  def edit
  end

  def show
  end

  def password
    @user = current_user
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = 'Seu usuário foi criado com sucesso!'
      redirect_to root_path
    else
      flash[:error] = "#{@user.errors.full_messages}"
      render action: "new"
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_path({ status: "user", notice: "#{User.model_name.human.capitalize} atualizado com sucesso" } ) }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def password_update
    @user = current_user
    @user.password = User.md5(params[:user][:password])
    @user.password_confirmation = User.md5(params[:user][:password_confirmation])

    respond_to do |format|
      if !params[:user][:password].blank? and @user.save
        session[:user_id] = @user.id
        @user.reload
        @user.save
        format.html { redirect_to root_path, notice: 'Sua senha foi alterada!' }
      else
        format.html { render action: "password", notice: 'Suas senhas não conferem!' }
      end
    end
  end

  def authenticate
    user = User.authenticate(params[:user][:email], params[:user][:password])
    if user
      session[:user_id] = user.id
      flash[:notice] = "Olá #{user.name}, bem vindo ao Portal de Variáveis!"
    else
      flash[:error] = "Usuário ou senha inválida"
      #redirect_to root_url
    end
    redirect_to root_url
  end

  def logout
    session[:user_id] = nil
    redirect_to root_url, :alert => "Obrigado por ter usado o Portal de Variáveis!"
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "#{User.model_name.human.capitalize} excluído com sucesso" }
      format.json { head :no_content }
    end
  end

  def remember_password_index
    @user = User.find(params[:id])
  end

  def remember_password
    @user = User.find(params[:id])
    @user.password = params[:user][:password]
    @user.password_confirmation = params[:user][:password_confirmation]

    if !params[:user][:password].blank? and @user.valid?
      @user.password = User.md5(params[:user][:password])
      @user.password_confirmation = User.md5(params[:user][:password_confirmation])
      @user.save
      redirect_to root_path, notice: "Sua senha do usuário #{@user.name} foi alterada!"
    else
      flash[:error] = "#{@user.errors.full_messages}"
      render action: "remember_password_index"
    end
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :name, :password, :password_confirmation, :role)
  end
end

app/views/users/_form.html.erb
<%= form_for(@user, html: {class: "nav-form"}) do |f| %>
  <div class="form">
    <div class="field t6">
      <%= f.label :name %><br>
      <%= f.text_field :name  %>
    </div>
    <div class="field t6">
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </div>
    <div class="field t7">
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
    <div class="field t7">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
    </div>

    <%= f.hidden_field :role, value: "user" %>

    <div class="field">
      <%= f.submit "Salvar" %>
      <%= link_to t('back'), users_path %>
    </div>
  </div>
<% end %>

app/views/users/_new_user.html.erb
<%= form_for @new_user do |u| %>
  <div id="newUser" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h2>Novo Usuário</h2>
    </div>
    <div class="modal-body">
    <% if @new_user.errors.any? %>
      <div class="alert alert-error">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <h4>Atenção!</h4>Os seguintes erros foram encontrados:
          <ul>
          <% @new_user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
      </div>
    <% end %>
      <div class="field">
        <span class="span3">Nome</span>
      </div>
      <div class="field">
        <div class="span3 input-append">
          <%= u.text_field :name, class: "span5" %>
        </div>
      </div>
      <div class="field">
        <span class="span3">Email</span>
      </div>
      <div class="field">
        <div class="span3 input-append">
          <%= u.text_field :email, class: "span5" %>
        </div>
      </div>
      <div class="field">
        <span class="span3">Time</span>
      </div>
      <div class="field">
        <span class="span3">Senha</span>
      </div>
      <div class="field">
        <div class="span3 input-append">
          <%= u.password_field :password, class: "password_field" %>
        </div>
      </div>
    </div>
    <div class="modal-footer">
      <%= u.submit "Salvar", class: "btn btn-primary" %>
      <%= link_to t('back'), users_path %>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<a name="forms-construido" class="link-ancora"></a>
<section>
  <h3 class="line-bottom">
    Cadastro de <%= User.model_name.human.capitalize %>:
    <span class="destaque">
      <%= @user.name %>
    </span>
  </h3>

  <%= form_for @user do |f| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> proibiram esse usuario de ser salvo:</h2>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <fieldset>

      <legend></legend>

      <div class="row clearfix">
        <div class="left t6">
          <%= f.label :name %>
          <%= f.text_field :name %>
        </div>
      </div>

      <div class="row clearfix">
        <div class="left t5">
          <%= f.label :email %>
          <%= f.text_field :email %>
        </div>
      </div>

      <div class="row clearfix">
        <div class="left t6">
          <%= f.label "Papel" %>
          <%= select_tag("user[role]", options_for_select([ ['Selecione um nível', ''], ['Administrador', 'admin'], ['Usuário', 'user']], @user.role), disabled: !@current_user.admin? ) %>
        </div>
      </div>

    </fieldset>

    <div class="actions">
      <%= f.submit "Salvar #{User.model_name.human.capitalize}" %>
    </div>

  <% end %>

</section>

app/views/users/index.html.erb
<div class="modulo">
  <div class="row-fluid">
    <h3>Usuários</h3>
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Nome</th>
          <th>Email</th>
          <th>Papel</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td>
              <% if @current_user.admin? %>
                <%= link_to user.name, edit_user_path(user.id) %>
              <% else %>
                <%= user.name %>
              <% end %>
            </td>
            <td><%= user.email %></td>
            <td><%= user.role %></td>
            <% if @current_user.admin? %>
              <td><%= link_to t("reset_password"), controller: "users", action: "remember_password_index", id: user.id %>
              <td><%= link_to t('destroy'), user, method: :delete, data: { confirm: t('are_you_sure') } %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
</div>

app/views/users/login.html.erb
<% unless flash.empty? %>
  <div>
    <%= render 'messages/message' %>
  </div>
<% end %>

<%= form_for("user", :url => "/signin") do |f| %>
  <h3>Login</h3>
  <div class="field t6">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field t6">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>

  <%= f.submit t('signin') %>
  <%= link_to t('new_user'), signup_path %>
<% end %>

app/views/users/new.html.erb
<% if flash[:notice] %>
  <div>
    <%=flash[:notice]%>
  </div>
<% end %>

<% if flash[:error] %>
  <div>
    <h4>Ooops!</h4>
    <%=flash[:error]%>
  </div>
<% end %>
<div class="span6">
  <h3>Cadastre-se</h3>
  <b>Novo Usuário</b>
  <legend></legend>
  <%= render 'form' %>
  <div class="controls">
    <span class="help-block">Você <span class="label label-important">não</span> receberá um e-mail para ativar sua conta.</span>
  </div>
</div>

app/views/users/password.html.erb
<div class="row-fluid">
  <div class="span5">
    <h3><%= @user.name %></h3>
    <legend></legend>
    <p>Não esqueça de anotar sua nova senha.</p>
    <%= form_for(@user, url: password_update_path, html: {class: "nav-form"}) do |f| %>
      <% if @user.errors.any? or notice %>
        <div class="alert alert-error">
          <button type="button" class="close" data-dismiss="alert">×</button>
          <h4>Atenção!</h4>
          Os seguintes erros foram encontrados:
          <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <div class="field">
        <%= f.password_field :password, placeholder:"Password", class: "span5"  %>
      </div>
      <div class="field">
        <%= f.password_field :password_confirmation, placeholder:"Confirmação", class: "span5"  %>
      </div>
      <div class="actions">
        <%= f.submit "Salvar", class: "btn btn-primary btn-inverse" %>
        <% unless @user %>
        <%= link_to 'Voltar', root_path, class: "btn btn-link" %>
        <% end %>
      </div>
    <% end %>
  </div><!-- div:span3 -->
</div><!-- div:row -->

app/views/users/remember_password_index.html.erb
<% if flash[:notice] %>
  <div>
    <%=flash[:notice]%>
  </div>
<% end %>

<% if flash[:error] %>
  <div>
    <h4>Ooops!</h4>
    <%=flash[:error]%>
  </div>
<% end %>

<%= form_for("user", :url => "/remember_password", id: @user.id) do |f| %>
  <h3>Redefinição de senha</h3>
  <div class="field">
    <%= f.label :name %><br>
    <%= @user.name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= @user.email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>

  <input type="hidden" name="id" value="<%= @user.id %>" %>

  <%= f.submit t("reset_password") %>
  <%= link_to t('back'), users_path %>
<% end %>

app/views/users/show.html.erb
<ul>
  <li><%= link_to @current_user.name, users_path %>/</li>
  <li><%= link_to 'Origens', origins_path %>/</li>
  <li><b><%= @user.name %></b></li>
</ul>
<div>
  <h3><%= @user.name %></h3>
</div>

app/views/users/signup.html.erb
<h1>Cadastre-se</h1>

<%= render 'form' %>